spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gym_pal
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
          timeout: 3000
    host: #SOMEHOST#
    username: #USERNAME#
    password: #PASSWORD#
    port: '587'
  banner:
    location: classpath:banner.txt
logging:
  level:
    root: INFO
